# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [3]:
df = pd.read_csv('SINASC_RO_2019.csv')
df.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27028 entries, 0 to 27027
Data columns (total 69 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ORIGEM        27028 non-null  int64
 1   CODESTAB      26913 non-null  float64
 2   CODMUNNASC    27028 non-null  int64
 3   LOCNASC       27028 non-null  int64
 4   IDADEMAE      27028 non-null  int64
 5   ESTCIVMAE     26711 non-null  float64
 6   ESCMAE        26716 non-null  object
 7   CODOCUPMAE    24121 non-null  float64
 8   QTDFILVIVO    25455 non-null  float64
 9   QTDFILMORT    24930 non-null  float64
 10  CODMUNRES     27028 non-null  int64
 11  GESTACAO      25796 non-null  object
 12  GRAVIDEZ      26949 non-null  object
 13  PARTO         26979 non-null  object
 14  CONSULTAS     27028 non-null  int64
 15  DTNASC        27028 non-null  object
 16  HORANASC      27007 non-null  float64
 17  SEXO          27024 non-null  object
 18  APGAR1        26932 non-null  float64
 19  APGAR5        26925 non-null  float64
 20  RACACOR       26381 non-null  object
 21  PESO          27028 non-null  int64
 22  IDANOMAL      26437 non-null  float64
 23  DTCADASTRO    27028 non-null  object
 24  CODANOMAL     214 non-null    object
 25  NUMEROLOTE    27028 non-null  int64
 26  VERSAOSIST    27028 non-null  object
 27  DTRECEBIM     27028 non-null  object
 28  DIFDATA       27028 non-null  int64
 29  DTRECORIGA    0 non-null      float64
 30  NATURALMAE    26730 non-null  float64
 31  CODMUNNATU    26730 non-null  float64
 32  CODUFNATU     26730 non-null  float64
 33  ESCMAE2010    26779 non-null  float64
 34  SERIESCMAE    14318 non-null  float64
 35  DTNASCMAE     26988 non-null  float64
 36  RACACORMAE    26367 non-null  float64
 37  QTDGESTANT    25816 non-null  float64
 38  QTDPARTNOR    25149 non-null  float64
 39  QTDPARTCES    25237 non-null  float64
 40  IDADEPAI      7607 non-null   float64
 41  DTULTMENST    16956 non-null  float64
 42  SEMAGESTAC    25790 non-null  float64
 43  TPMETESTIM    25790 non-null  float64
 44  CONSPRENAT    26098 non-null  float64
 45  MESPRENAT     24161 non-null  float64
 46  TPAPRESENT    26763 non-null  float64
 47  STTRABPART    26081 non-null  float64
 48  STCESPARTO    26281 non-null  float64
 49  TPNASCASSI    26967 non-null  float64
 50  TPFUNCRESP    26961 non-null  float64
 51  TPDOCRESP     27014 non-null  float64
 52  DTDECLARAC    26976 non-null  float64
 53  ESCMAEAGR1    26779 non-null  float64
 54  STDNEPIDEM    27028 non-null  int64
 55  STDNNOVA      27028 non-null  int64
 56  CODPAISRES    27028 non-null  int64
 57  TPROBSON      27028 non-null  int64
 58  PARIDADE      27028 non-null  int64
 59  KOTELCHUCK    27028 non-null  int64
 60  CONTADOR      27028 non-null  int64
 61  munResStatus  27028 non-null  object
 62  munResTipo    27028 non-null  object
 63  munResNome    27028 non-null  object
 64  munResUf      27028 non-null  object
 65  munResLat     27027 non-null  float64
 66  munResLon     27027 non-null  float64
 67  munResAlt     27027 non-null  float64
 68  munResArea    27027 non-null  float64
dtypes: float64(38), int64(16), object(15)
memory usage: 14.2+ MB

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [7]:
df.groupby('munResNome')[['IDADEMAE', 'IDADEPAI']].mean()

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [9]:
df.groupby(['SEXO','DTNASC','ESCMAE'])['PESO'].mean()

SEXO       DTNASC      ESCMAE
Feminino   2019-01-01  12 anos ou mais    3370.000000
                       4 a 7 anos         3536.250000
                       8 a 11 anos        3193.928571
           2019-01-02  12 anos ou mais    2841.285714
                       4 a 7 anos         3175.000000
                                             ...
Masculino  2019-12-30  8 a 11 anos        3278.684211
           2019-12-31  1 a 3 anos         2895.000000
                       12 anos ou mais    3348.333333
                       4 a 7 anos         3511.888889
                       8 a 11 anos        3354.166667
Name: PESO, Length: 2586, dtype: float64

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [47]:
# Castanheiras
df.munResNome.value_counts().sort_values()

municipio = df[df['munResNome'] == 'Castanheiras']

municipio = municipio[['IDADEMAE', 'munResNome', 'IDADEPAI']]


municipio.aggregate([max, 'min', 'mean'])

      IDADEMAE    munResNome   IDADEPAI
max   39.00000  Castanheiras  43.000000
min   17.00000  Castanheiras  17.000000
mean  27.28125           NaN  30.392857

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [39]:
df.loc[:, 'DTNASC'] = pd.to_datetime(df['DTNASC'])
df['Mês'] = df['DTNASC'].dt.strftime('%B')

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea,Mês
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025,February
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025,February
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025,February
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273,March
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,1,2604388.0,510340,1,32,2.0,12 anos ou mais,333115.0,1.0,0.0,...,2767632,ATIVO,MUNIC,Vilhena,Rondônia,-12.74137,-60.13858,595.0,11518.915,December
27024,1,2752654.0,510675,1,19,1.0,8 a 11 anos,999992.0,0.0,0.0,...,2772678,ATIVO,MUNIC,Chupinguaia,Rondônia,-12.55684,-60.90185,340.0,5126.723,October
27025,1,9659366.0,510787,1,24,2.0,8 a 11 anos,421125.0,0.0,1.0,...,2776905,ATIVO,MUNIC,Vilhena,Rondônia,-12.74137,-60.13858,595.0,11518.915,August
27026,1,9659366.0,510787,1,21,2.0,8 a 11 anos,999992.0,1.0,0.0,...,2777105,ATIVO,MUNIC,Vilhena,Rondônia,-12.74137,-60.13858,595.0,11518.915,December
27027,1,2795655.0,510792,1,18,5.0,8 a 11 anos,999992.0,1.0,0.0,...,2780269,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia,-11.70974,-61.99439,230.0,843.446,December

In [48]:
df_marco = df[df['Mês'] == 'March']
df_marco.munResNome.value_counts().sort_values(ascending=False)

df_marco_municipio = df[df['munResNome'] == 'Castanheiras']

df_marco_municipio = df_marco_municipio[['QTDFILVIVO', 'IDADEPAI', 'IDADEMAE']]

df_marco_municipio.aggregate([max, 'min', 'mean'])

      QTDFILVIVO   IDADEPAI  IDADEMAE
max       6.0000  43.000000  39.00000
min       0.0000  17.000000  17.00000
mean      1.0625  30.392857  27.28125

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Castanheiras é o munícipio que menos nasceu bebê em 2019, o que pode ser justificado pela sua população de 2.987 (2020).